export const VesperTheme = {
  inherit: false,
  base: "vs-dark",
  colors: {
    "editor.background": "#121113",
    "editor.foreground": "#ffffff",
    "editor.selectionBackground": "#FFFFFF10",
    "editor.selectionHighlightBackground": "#FFFFFF10",
    "editorLineNumber.foreground": "#505050",
    "editorGroupHeader.tabsBackground": "#121113",
    "editorWidget.background": "#121113",
    "editorWarning.foreground": "#FFC799",
    "editorError.foreground": "#FF8080",
    "editorOverviewRuler.border": "#121113",
    "editorGutter.addedBackground": "#99FFE4",
    "editorGutter.deletedBackground": "#FF8080",
    "editorGutter.modifiedBackground": "#FFC799",
    "diffEditor.insertedTextBackground": "#99FFE415",
    "diffEditor.insertedLineBackground": "#99FFE415",
    "diffEditor.removedTextBackground": "#FF808015",
    "diffEditor.removedLineBackground": "#FF808015",
    "editorInlayHint.foreground": "#505050",
    "editorInlayHint.background": "#161616",
    "sideBar.background": "#121113",
    "sideBarTitle.foreground": "#A0A0A0",
    "sideBarSectionHeader.foreground": "#A0A0A0",
    "sideBarSectionHeader.background": "#121113",
    "activityBar.background": "#121113",
    "activityBar.foreground": "#A0A0A0",
    "activityBarBadge.background": "#FFC799",
    "activityBarBadge.foreground": "#121113",
    "titleBar.activeBackground": "#121113",
    "titleBar.inactiveBackground": "#121113",
    "titleBar.activeForeground": "#A0A0A0",
    "titleBar.inactiveForeground": "#505050",
    "tab.border": "#121113",
    "tab.activeBackground": "#121113",
    "tab.activeBorder": "#FFC799",
    "tab.inactiveBackground": "#121113",
    "statusBar.debuggingForeground": "#121113",
    "statusBar.debuggingBackground": "#FFC799",
    "statusBar.background": "#121113",
    "statusBar.foreground": "#A0A0A0",
    "statusBarItem.remoteBackground": "#FFC799",
    "statusBarItem.remoteForeground": "#121113",
    "list.activeSelectionForeground": "#FFC799",
    "list.inactiveSelectionBackground": "#161616",
    "badge.background": "#FFC799",
    "badge.foreground": "#121113",
    "button.background": "#FFC799",
    "button.hoverBackground": "#FFD4B2",
    "button.foreground": "#121113",
    focusBorder: "#FFC799",
    "icon.foreground": "#A0A0A0",
    "input.background": "#161616",
    "list.activeSelectionBackground": "#161616",
    "list.hoverBackground": "#161616",
    "list.errorForeground": "#FF8080",
    "list.highlightForeground": "#FFC799",
    "selection.background": "#FFFFFF10",
    "editorBracketHighlight.foreground1": "#A0A0A0",
    "editorBracketHighlight.foreground2": "#A0A0A0",
    "editorBracketHighlight.foreground3": "#A0A0A0",
    "editorBracketHighlight.foreground4": "#A0A0A0",
    "editorBracketHighlight.foreground5": "#A0A0A0",
    "editorBracketHighlight.foreground6": "#A0A0A0",
    "editorBracketHighlight.unexpectedBracket.foreground": "#FF8080",
    "textLink.foreground": "#FFC799",
    "textLink.activeForeground": "#FFD4B2",
    "editorHoverWidget.background": "#161616",
    "editorHoverWidget.border": "#252525",
    "scrollbarSlider.background": "#FFFFFF10",
    "scrollbarSlider.hoverBackground": "#FFFFFF20",
    "settings.modifiedItemIndicator": "#FFC799",
  },
  rules: [
    { token: "string.key", foreground: "#FFC799" },
    { token: "string.value", foreground: "#99FFE4" },
    { token: "string", foreground: "#99FFE4" },
    { token: "number", foreground: "#FFC799" },
    { token: "keyword", foreground: "#A0A0A0" },
    { token: "delimiter", foreground: "#ffffff" },
    { token: "comment", foreground: "#505050", fontStyle: "italic" },
    { token: "variable", foreground: "#A0A0A0" },
    { token: "type", foreground: "#FFC799" },
    { token: "class", foreground: "#FFC799" },
    { token: "function", foreground: "#FFC799" },
    { token: "constant", foreground: "#A0A0A0" },
  ],
};
