export const VesperLightTheme = {
  inherit: false,
  base: "vs",
  colors: {
    "editor.background": "#ffffff",
    "editor.foreground": "#101010",
    "editor.selectionBackground": "#00000010",
    "editor.selectionHighlightBackground": "#00000010",
    "editorLineNumber.foreground": "#A0A0A0",
    "editorGroupHeader.tabsBackground": "#ffffff",
    "editorWidget.background": "#f5f5f5",
    "editorWarning.foreground": "#d97706",
    "editorError.foreground": "#ef4444",
    "editorOverviewRuler.border": "#ffffff",
    "editorGutter.addedBackground": "#10b981",
    "editorGutter.deletedBackground": "#ef4444",
    "editorGutter.modifiedBackground": "#f59e0b",
    "diffEditor.insertedTextBackground": "#10b98115",
    "diffEditor.insertedLineBackground": "#10b98115",
    "diffEditor.removedTextBackground": "#ef444415",
    "diffEditor.removedLineBackground": "#ef444415",
    "editorInlayHint.foreground": "#9ca3af",
    "editorInlayHint.background": "#f3f4f6",
    "sideBar.background": "#f9fafb",
    "sideBarTitle.foreground": "#6b7280",
    "sideBarSectionHeader.foreground": "#6b7280",
    "sideBarSectionHeader.background": "#f9fafb",
    "activityBar.background": "#f9fafb",
    "activityBar.foreground": "#6b7280",
    "activityBarBadge.background": "#d97706",
    "activityBarBadge.foreground": "#ffffff",
    "titleBar.activeBackground": "#ffffff",
    "titleBar.inactiveBackground": "#f9fafb",
    "titleBar.activeForeground": "#111827",
    "titleBar.inactiveForeground": "#6b7280",
    "tab.border": "#e5e7eb",
    "tab.activeBackground": "#ffffff",
    "tab.activeBorder": "#d97706",
    "tab.inactiveBackground": "#f9fafb",
    "statusBar.debuggingForeground": "#ffffff",
    "statusBar.debuggingBackground": "#d97706",
    "statusBar.background": "#ffffff",
    "statusBar.foreground": "#6b7280",
    "statusBarItem.remoteBackground": "#d97706",
    "statusBarItem.remoteForeground": "#ffffff",
    "list.activeSelectionForeground": "#d97706",
    "list.inactiveSelectionBackground": "#f3f4f6",
    "badge.background": "#d97706",
    "badge.foreground": "#ffffff",
    "button.background": "#d97706",
    "button.hoverBackground": "#f59e0b",
    "button.foreground": "#ffffff",
    focusBorder: "#d97706",
    "icon.foreground": "#6b7280",
    "input.background": "#ffffff",
    "list.activeSelectionBackground": "#f3f4f6",
    "list.hoverBackground": "#f9fafb",
    "list.errorForeground": "#ef4444",
    "list.highlightForeground": "#d97706",
    "selection.background": "#e5e7eb",
    "editorBracketHighlight.foreground1": "#6b7280",
    "editorBracketHighlight.foreground2": "#6b7280",
    "editorBracketHighlight.foreground3": "#6b7280",
    "editorBracketHighlight.foreground4": "#6b7280",
    "editorBracketHighlight.foreground5": "#6b7280",
    "editorBracketHighlight.foreground6": "#6b7280",
    "editorBracketHighlight.unexpectedBracket.foreground": "#ef4444",
    "textLink.foreground": "#d97706",
    "textLink.activeForeground": "#f59e0b",
    "editorHoverWidget.background": "#ffffff",
    "editorHoverWidget.border": "#e5e7eb",
    "scrollbarSlider.background": "#00000020",
    "scrollbarSlider.hoverBackground": "#00000030",
    "settings.modifiedItemIndicator": "#d97706",
  },
  rules: [
    { token: "string.key", foreground: "#101010" },
    { token: "string.value", foreground: "#c45c21" },
    { token: "string", foreground: "#1e7252" },
    { token: "number", foreground: "#c45c21" },
    { token: "keyword", foreground: "#c45c21" },
    { token: "delimiter", foreground: "#6b7280" },
    { token: "comment", foreground: "#888888", fontStyle: "italic" },
    { token: "variable", foreground: "#101010" },
    { token: "type", foreground: "#c45c21" },
    { token: "class", foreground: "#c45c21" },
    { token: "function", foreground: "#c45c21" },
    { token: "constant", foreground: "#c45c21" },
  ],
};
